[package]
name = "dnsimple-rust-sample-code-list-domains"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dnsimple = "0.1.2"
